---
sudo: required
language: nodejs
services:
  - docker
script:
  - docker build -t hcaptcha/hmt-token .
  - "./bin/test"
notifications:
  slack:
    matrix:
      - intuitionmachines:UI7rZpykdTnS2Raz6l3ODIWo
    rooms:
      secure: CpCosPb/tsPgOn8Pqtu4Wl50YoPcvCvffD2+r9KkfWAHV9K9MnNmTWwBFR7g1RDHFH3vnmkUSD7LcyoGeu8OjH5w+LsrQWHVaK2Ou24S+UL1kpWdprMsXUm8q8mKm16Tmz3EBGBwFV+bqrdELw3cl7H5/fCe20+CywjexSjxD9IyTesA5v5xRg+ZP8Iil1ynhkMoRXFHBkHrSoiGQ8orMjVnty7TmvaOp0vKznoUleomne6huRvDSef63oJGQfnknmbwYk6BYmqSqvmgV8KJB5RO4UJ9vcZUFKSziEtLGRD0/A2osyyBODVhyTdAQnGZIx058/RVxZo1UbNX2vb4ZPDLCYiFMHnjtTgOalKOJ/3C24S+oznMLZCFQgNHYU1zYpBOe0dpUAxy2LVCRsYFncjLb9DcMjDlH/cuPKBU/rIuhKWBjhOwrEo0SQQ8MCySMR36Rm6o+c2zbUPUjxXDUAyptEemq9KfGU8i6wcJxPp4TCvqT8C3ZBc9z1uHu/uHkakc18Sm5BoOLTi3ynDZq8IJ3WSrMiMUelJL9PGiptN5V1lBecAqfLq5lEhz0VYJ0fqoNuBh1N9EClDHlYWApIDbWRhdyWbX/cimhnqojNJaOXfJrlHJId9AB0X+Po/nRlAQC5okCMZq3xkOYvFhWe4ONl9eP2qxtXKKyj4CySw=
