version: '2'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
  hmt:
    build: .
    image: hcaptcha/hmt-token
    environment:
      - ETH_HOST=ganache
      - ETH_PORT=8545
    links:
      - ganache
